# Generated by Django 4.2.4 on 2023-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='login.member')),
            ],
        ),
    ]
